# Generated by Django 3.1.3 on 2023-03-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230305_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='choice sample text', max_length=200),
        ),
    ]
